Repository hassio-addons/addon-plex, pull requests merged in 2024-02, with the labels that each got.

#215 Add support for more Intel based Hardware Acceleration
  plex/config.yaml
Labels: bugfix

#216 Update logo/icon to current version.
  plex/icon.png
  plex/logo.png
Labels: maintenance

#219 ⬆️ Upgrades base image to 7.3.3
  plex/Dockerfile
  plex/build.yaml
Labels: dependencies

#220 ⬆️ Upgrades Plex Media Server to 1.40.0.7998
  plex/Dockerfile
Labels: dependencies, minor
