Repository hassio-addons/addon-plex, pull requests merged in 2024-01, with the labels that each got.

#214 Migrate from Ubuntu to Debian
  plex/Dockerfile
  plex/build.yaml
Labels: enhancement

#213 :fireworks: Updates maintenance/license year to 2024
  LICENSE.md
  README.md
  plex/.README.j2
  plex/DOCS.md
Labels: maintenance

#212 Install version 1.32.8.7639 of Plex Media Server
  plex/Dockerfile
Labels: dependencies
